[package]
name = "repoviewer"
version = "0.1.0"
edition = "2021"

<<<<<<< HEAD
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
=======
[dependencies]
octocrab = "0.34.1"
>>>>>>> 47ceadd (Starting project)
